version: '3.4'

services:
  mysql:
    image: mysql
    container_name: ${PROJECT_NAME}-mysql
    expose:
      - "3306"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./compose/mysql/data:/var/lib/mysql
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - services

  minio:
    image: quay.io/minio/minio
    container_name: ${PROJECT_NAME}-minio
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - ${MINIO_SERVER_PORT}:9000
      - ${MINIO_WEB_PORT}:9001
    volumes:
      - ./compose/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - services

  redis:
    image: docker.io/library/redis:latest
    container_name: ${PROJECT_NAME}-redis
    restart: always
    expose:
      - "6379"
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./compose/redis/data:/data
      - ./compose/redis/conf/redis.conf:/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - services

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${PROJECT_NAME}-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    expose:
      - "5672"
      - "15672"
    ports:
      - ${RABBITMQ_SERVER_PORT}:5672
      - ${RABBITMQ_WEB_PORT}:15672
    volumes:
        - ./compose/rabbitmq/data:/bitnami/rabbitmq/mnesia
    networks:
      - services

  elasticsearch:
    container_name: ${PROJECT_NAME}-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    restart: always
    expose:
      - "9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./compose/elasticsearch/data:/usr/share/elasticsearch/data
      - ./compose/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - services

networks:
  services: # TODO: 修改
    driver: bridge
